import React from 'react';
import { useState, useEffect, useRef } from 'react';
import {
    Button,
    Image,
    Input,
    List,
    Select,
    Steps,
    Radio,
} from 'antd';


const { Step } = Steps;

const WizardStep = (props) => {
    const [stepIndex, setStepIndex] = useState(-1);
    const [showResult, setShowResult] = useState(false);
    const [configuration, setConfiguration] = useState([]);
    const [advanceStep, setAdvanceStep] = useState(false);
    const downloadParentRef = useRef(null);

    const onRestart = () => {
        setConfiguration([]);
        setStepIndex(0);
        setShowResult(false);
    };

    useEffect(() => {
        let nextStepIndex = stepIndex + 1;

        // Check whether the current step needs to be skipped
        let skip = true;
        while (nextStepIndex < stepProps.length) {
            skip = false;
            let nextStep = stepProps[nextStepIndex];
            if (nextStep.conditions) {
                let result = true;
                nextStep.conditions.forEach(cond => {
                    const neededKeys = cond.neededKeys.split(',');
                    const conf = configuration.find(config => config.variable === cond.variable);
                    if (!conf || (neededKeys.indexOf(conf.value) === -1)) {
                        result = false;
                    }
                });

                if (!result) {
                    skip = true;
                }
            }

            if (!skip) {
                setStepIndex(nextStepIndex);
                break;
            }
            else {
                nextStepIndex++;
            }
        }

        if (skip) {
            setStepIndex(nextStepIndex);
            setShowResult(true);
        }
    }, [advanceStep]);

    const downloadTxtFile = (lines) => {
        const element = document.createElement("a");
        const file = new Blob([...(lines.map(line => line + "\n"))], { type: 'text/plain;charset=utf-8' });
        element.setAttribute('href', window.URL.createObjectURL(file));

        element.target = "_blank";
        element.rel = "noreferrer noopener";
        //element.download = "Configuration_local.hpp";
        downloadParentRef.current.appendChild(element);
        setTimeout(function () {
            element.click();
            element.parentNode.removeChild(element);
        }, 200);

    }

    const onSelect = (index, e) => {
        let newConfiguration = configuration.filter(config => config.variable !== stepProps[index].variable)
        newConfiguration = [...newConfiguration, { variable: stepProps[index].variable, value: e }]
        setConfiguration(newConfiguration);
        setAdvanceStep(!advanceStep);
    }

    const onChangedText = (index, key, val) => {
        if (key === '$OK') {
            setAdvanceStep(!advanceStep);
        }
        else {
            let currentConfig = configuration.find(config => config.variable === stepProps[index].variable) || { value: [] };
            let newConfig = currentConfig.value.filter(config => config.key !== key);
            newConfig = [...newConfig, { key: key, value: val }];
            let newConfiguration = configuration.filter(config => config.variable !== stepProps[index].variable);
            newConfiguration = [...newConfiguration, { variable: stepProps[index].variable, value: newConfig }]
            setConfiguration(newConfiguration);
        }
    }

    const stepProps = [
        {
            title: 'Hemisphere',
            label: 'Which hemisphere do you live in:',
            variable: 'hemi',
            preamble: [
                '/////////////////////////////////////////////////////////////////////////////////////////////////////////',
                '// This configuration file was generated by the OAT Configurator at https://config.openastrotech.com',
                '// Save this as Configuration_local.hpp in the folder where you placed the firmware code.',
                '',
                '// We live in the {v}'],
            define: 'NORTHERN_HEMISPHERE',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'N', value: 'Northern Hemisphere', image: '/images/north.png', defineValue: '1' },
                    { key: 'S', value: 'Southern Hemisphere', image: '/images/south.png', defineValue: '0' }]
            },
            //control: { type: 'combo', choices: [{key:'N', value:'Northern Hemisphere'}, {key:'S', value:'Southern Hemisphere'}] },
        },
        {
            title: 'Board',
            label: 'Which microcontroller board are you using:',
            variable: 'board',
            preamble: ['// We are using the {v} board'],
            define: 'BOARD',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'M', value: 'ATMega 2560 (or clone)', image: '/images/mega2560.png', defineValue: 'BOARD_AVR_MEGA2560' },
                    { key: 'E', value: 'ESP32', image: '/images/esp32.png', defineValue: 'BOARD_ESP32_ESP32DEV' },
                    { key: 'K1', value: 'MKS GEN L V1.0', image: '/images/mksv10.png', defineValue: 'BOARD_AVR_MKS_GEN_L_V1' },
                    { key: 'K20', value: 'MKS GEN L V2.0', image: '/images/mksv20.png', defineValue: 'BOARD_AVR_MKS_GEN_L_V2' },
                    { key: 'K21', value: 'MKS GEN L V2.1', image: '/images/mksv21.png', defineValue: 'BOARD_AVR_MKS_GEN_L_V21' },
                ]
            },
        },
        {
            title: 'RA Stepper',
            label: 'Which stepper motor are you using for RA:',
            variable: 'ra',
            preamble: ['// Stepper types/models', ' // See supported stepper values. Change according to the steppers you are using', '// Using the {v} stepper for RA'],
            define: 'RA_STEPPER_TYPE',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'B', value: '28BYJ-48', image: '/images/byj48.png', defineValue: 'STEPPER_TYPE_28BYJ48', additionalLines: ['#define RA_DRIVER_TYPE DRIVER_TYPE_ULN2003'] },
                    { key: 'N', value: 'NEMA 17, 0.9°/step', image: '/images/nema17.png', defineValue: 'STEPPER_TYPE_NEMA17' },
                    { key: 'P', value: 'NEMA 17, 1.8°/step', image: '/images/nema17.png', defineValue: 'STEPPER_TYPE_NEMA17', additionalLines: ['#define RA_STEPPER_SPR 200'] },
                ]
            },
        },
        {
            title: 'RA Driver',
            label: 'Which driver board are you using to drive the RA stepper motor:',
            variable: 'radrv',
            conditions: [{ variable: 'ra', neededKeys: 'N,P' }],
            preamble: ['// Using the {v} driver for RA stepper motor'],
            define: 'RA_DRIVER_TYPE',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'U', value: 'ULN2003', image: '/images/uln2003.png', defineValue: 'DRIVER_TYPE_ULN2003' },
                    { key: 'A', value: 'Generic A4988', image: '/images/a4988.png', defineValue: 'DRIVER_TYPE_A4988_GENERIC' },
                    { key: 'T9U', value: 'TMC2209-UART', image: '/images/tmc2209.png', defineValue: 'DRIVER_TYPE_TMC2209_UART' },
                    { key: 'T9S', value: 'TMC2209-Standalone', image: '/images/tmc2209.png', defineValue: 'DRIVER_TYPE_TMC2209_STANDALONE' },
                ]
            },
        },
        {
            title: 'RA Advanced Settings',
            label: 'Enter the RA stepper specs and desired settings:',
            variable: 'rapower',
            conditions: [{ variable: 'radrv', neededKeys: 'T9U' }],
            define: '',
            control: {
                type: 'textinput',
                choices: [
                    { key: 'P', label: 'Power rating in mA', defaultValue: 250, defineLine: '#define RA_MOTOR_CURRENT_RATING      {0} // mA' },
                    { key: 'O', label: 'Operating percentage', defaultValue: 80, defineLine: '#define RA_OPERATING_CURRENT_SETTING {0} // %' },
                    { key: 'A', label: 'Acceleration (steps/s/s)', defaultValue: 3000, defineLine: '#define RA_STEPPER_ACCELERATION {0}' },
                    { key: 'S', label: 'Microstepping while slewing', defaultValue: 8, defineLine: '#define RA_SLEW_MICROSTEPPING {0}' },
                    { key: 'T', label: 'Microstepping while tracking', defaultValue: 64, defineLine: '#define RA_TRACKING_MICROSTEPPING {0}', additionalLines:['// #define RA_SERIAL_PORT Serial3  // You may need to uncomment or change this, depending on how you wired the UART'] },
                ]
            },
        },
        {
            title: 'RA Pulley Teeth',
            label: 'How many teeth does your RA gear have?',
            variable: 'racog',
            preamble: ['// Using the {v} for RA belt'],
            define: 'RA_PULLEY_TEETH',
            control: {
                type: 'radioimg',
                choices: [
                    { key: '1', value: '16 tooth purchased gear', image: '/images/cog16t.png', defineValue: '16' },
                    { key: '2', value: '20 tooth printed gear', image: '/images/cog20t.png', defineValue: '20' },
                ]
            },
        },
        {
            title: 'DEC Stepper',
            label: 'Which stepper motor are you using for DEC:',
            variable: 'dec',
            preamble: ['// Stepper types/models', ' // See supported stepper values. Change according to the steppers you are using', '// Using the {v} stepper for DEC'],
            define: 'DEC_STEPPER_TYPE',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'B', value: '28BYJ-48', image: '/images/byj48.png', defineValue: 'STEPPER_TYPE_28BYJ48', additionalLines: ['#define DEC_DRIVER_TYPE DRIVER_TYPE_ULN2003']  },
                    { key: 'N9', value: 'NEMA 17, 0.9°/step', image: '/images/nema17.png', defineValue: 'STEPPER_TYPE_NEMA17' },
                    { key: 'N8', value: 'NEMA 17, 1.8°/step', image: '/images/nema17.png', defineValue: 'STEPPER_TYPE_NEMA17', additionalLines: ['#define DEC_STEPPER_SPR 200'] },
                    { key: 'P9', value: 'NEMA 14, 0.9°/step', image: '/images/nema14.png', defineValue: 'STEPPER_TYPE_NEMA17' },
                    { key: 'P8', value: 'NEMA 14, 1.8°/step', image: '/images/nema14.png', defineValue: 'STEPPER_TYPE_NEMA17', additionalLines: ['#define DEC_STEPPER_SPR 200'] },
                ]
            },
        },
        {
            title: 'DEC Driver',
            label: 'Which driver board are you using to drive the DEC stepper motor:',
            variable: 'decdrv',
            conditions: [{ variable: 'dec', neededKeys: 'N9,N8,P9,P8' }],
            preamble: ['// Using the {v} driver for DEC stepper'],
            define: 'DEC_DRIVER_TYPE',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'U', value: 'ULN2003', image: '/images/uln2003.png', defineValue: 'DRIVER_TYPE_ULN2003' },
                    { key: 'A', value: 'Generic A4988', image: '/images/a4988.png', defineValue: 'DRIVER_TYPE_A4988_GENERIC' },
                    { key: 'T9U', value: 'TMC2209-UART', image: '/images/tmc2209.png', defineValue: 'DRIVER_TYPE_TMC2209_UART' },
                    { key: 'T9S', value: 'TMC2209-Standalone', image: '/images/tmc2209.png', defineValue: 'DRIVER_TYPE_TMC2209_STANDALONE' },
                ]
            },
        },
        {
            title: 'DEC Advanced Settings',
            label: 'Enter the DEC stepper specs and desired settings:',
            variable: 'decpower',
            conditions: [{ variable: 'decdrv', neededKeys: 'T9U' }],
            define: '',
            control: {
                type: 'textinput',
                choices: [
                    { key: 'P', label: 'Power rating in mA', defaultValue: 250, defineLine: '#define DEC_MOTOR_CURRENT_RATING      {0} // mA' },
                    { key: 'O', label: 'Operating percentage', defaultValue: 80, defineLine: '#define DEC_OPERATING_CURRENT_SETTING {0} // %' },
                    { key: 'A', label: 'Acceleration (steps/s/s)', defaultValue: 3000, defineLine: '#define DEC_STEPPER_ACCELERATION {0}' },
                    { key: 'S', label: 'Microstepping while slewing', defaultValue: 16, defineLine: '#define DEC_SLEW_MICROSTEPPING {0}' },
                    { key: 'T', label: 'Microstepping while tracking', defaultValue: 64, defineLine: '#define DEC_GUIDE_MICROSTEPPING {0}', additionalLines:['// #define DEC_SERIAL_PORT Serial3  // You may need to uncomment or change this, depending on how you wired the UART']  },
                ]
            },
        },
        {
            title: 'DEC Pulley Teeth',
            label: 'How many teeth does your DEC gear have?',
            variable: 'deccog',
            preamble: ['// Using the {v} for DEC belt'],
            define: 'DEC_PULLEY_TEETH',
            control: {
                type: 'radioimg',
                choices: [
                    { key: '1', value: '16 tooth purchased gear', image: '/images/cog16t.png', defineValue: '16' },
                    { key: '2', value: '20 tooth printed gear', image: '/images/cog20t.png', defineValue: '20' },
                ]
            },
        },
        {
            title: 'Display',
            label: 'What kind of display are you using:',
            variable: 'disp',
            define: 'DISPLAY_TYPE',
            preamble: ['// Define the type of display we are using. Currently {v}'],
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'N', value: 'No display', image: '/images/none.png', defineValue: 'DISPLAY_TYPE_NONE' },
                    { key: 'L', value: 'LCD Shield w/ keypad', image: '/images/lcdshield.png', defineValue: 'DISPLAY_TYPE_LCD_KEYPAD' },
                    { key: 'I08', value: 'I2C LCD Shield w/ MCP23008 controller', image: '/images/lcd23008.png', defineValue: 'DISPLAY_TYPE_LCD_KEYPAD_I2C_MCP23008' },
                    { key: 'I17', value: 'I2C LCD Shield w/ MCP23017 controller', image: '/images/lcd23017.png', defineValue: 'DISPLAY_TYPE_LCD_KEYPAD_I2C_MCP23017' },
                    { key: 'S13', value: 'I2C 32x128 OLED w/ joystick', image: '/images/ssd1306.png', defineValue: 'DISPLAY_TYPE_LCD_JOY_I2C_SSD1306' },
                ]
            },
        },
        {
            title: 'Use WiFi',
            label: 'Do you want to enable WiFi:',
            variable: 'wifi',
            conditions: [{ variable: 'board', neededKeys: 'E' }],
            preamble: ['// Are we using WiFi: {v}'],
            define: 'WIFI_ENABLED',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'Y', value: 'Yes, use WiFi', image: '/images/wifi.png', defineValue: '1' },
                    { key: 'N', value: 'No, disable WiFi', image: '/images/nowifi.png', defineValue: '0' },
                ]
            },
        },
        {
            title: 'WiFi Mode',
            label: 'In what mode do you want to use WiFi:',
            conditions: [{ variable: 'wifi', neededKeys: 'Y' }],
            variable: 'wifimode',
            preamble: ['// Using WiFi in mode {v}'],
            define: 'WIFI_MODE',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'I', value: 'Infrastructure, all devices connect to same network', image: '/images/infra.png', defineValue: 'WIFI_MODE_INFRASTRUCTURE' },
                    { key: 'A', value: 'Access Point, OAT is a hotspot', image: '/images/ap.png', defineValue: 'WIFI_MODE_AP_ONLY' },
                    { key: 'F', value: 'Infrastructure with failover to Access Point', image: '/images/failover.png', defineValue: 'WIFI_MODE_ATTEMPT_INFRASTRUCTURE_FAIL_TO_AP' },
                ]
            },
        },
        {
            title: 'WiFi Infrastructure Setup',
            label: 'Enter the WiFi parameters for Infrastructure mode:',
            variable: 'wifiparamsi',
            conditions: [
                { variable: 'wifi', neededKeys: 'Y' },
                { variable: 'wifimode', neededKeys: 'I' },
            ],
            preamble: ['// Define the SSID, WPA key and host name for the network'],
            define: '',
            control: {
                type: 'textinput',
                choices: [
                    { key: 'S', label: 'WiFi SSID', defineLine: '#define WIFI_INFRASTRUCTURE_MODE_SSID "{0}"' },
                    { key: 'P', label: 'WPA Key', defineLine: '#define WIFI_INFRASTRUCTURE_MODE_WPAKEY "{0}"' },
                    { key: 'H', label: 'Hostname', defaultValue: 'OATScope', defineLine: '#define WIFI_HOSTNAME "{0}"' },
                ]
            },
        },
        {
            title: 'WiFi Access Point Setup',
            label: 'Enter the WiFi parameters for Access Point mode:',
            variable: 'wifiparamsa',
            conditions: [
                { variable: 'wifi', neededKeys: 'Y' },
                { variable: 'wifimode', neededKeys: 'A' },
            ],
            define: '',
            preamble: ['// Define the WPA key and host name for the network'],
            control: {
                type: 'textinput',
                choices: [
                    { key: 'P', label: 'WPA Key for OAT hotspot', defineLine: '#define WIFI_AP_MODE_WPAKEY "{0}"' },
                    { key: 'H', label: 'Hostname', defaultValue: 'OATScope', defineLine: '#define WIFI_HOSTNAME "{0}"' },
                ]
            },
        },
        {
            title: 'WiFi Failover Setup',
            label: 'Enter the WiFi parameters for Failover mode:',
            variable: 'wifiparamsf',
            conditions: [
                { variable: 'wifi', neededKeys: 'Y' },
                { variable: 'wifimode', neededKeys: 'F' },
            ],
            define: '',
            preamble: ['// Define the SSID, WPA keys and host name for the network'],
            control: {
                type: 'textinput',
                choices: [
                    { key: 'S', label: 'WiFi SSID of network', defineLine: '#define WIFI_INFRASTRUCTURE_MODE_SSID "{0}"' },
                    { key: 'P', label: 'WPA Key for network', defineLine: '#define WIFI_INFRASTRUCTURE_MODE_WPAKEY "{0}"' },
                    { key: 'N', label: 'WPA Key for OAT hotspot', defineLine: '#define WIFI_AP_MODE_WPAKEY "{0}"' },
                    { key: 'H', label: 'Hostname', defaultValue: 'OATScope', defineLine: '#define WIFI_HOSTNAME "{0}"' },
                ]
            },
        },
        {
            title: 'GPS',
            label: 'Do you have the GPS add on:',
            variable: 'gps',
            preamble: ['// Define whether we have the GPS addon or not. Currently: {v}'],
            define: 'USE_GPS',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'N', value: 'No GPS', image: '/images/none.png', defineValue: '0' },
                    { key: 'Y', value: 'GPS NEO-6M', image: '/images/gpsneo6m.png', defineValue: '1' },
                ]
            },
        },
        {
            title: 'Level',
            label: 'Do you have the Digital Level add on:',
            variable: 'gyro',
            preamble: ['// Define whether we have the Digital Level or not. Currently: {v}'],
            define: 'USE_GYRO_LEVEL',
            control: {
                type: 'radioimg',
                choices: [
                    { key: 'N', value: 'No Digital Level', image: '/images/none.png', defineValue: '0' },
                    { key: 'Y', value: 'MPU-6050 Gyroscope', image: '/images/levelmpu6050.png', defineValue: '1', additionalLines: ['#define GYRO_AXIS_SWAP 0'] },
                    { key: 'Y2', value: 'MPU-6050 Gyroscope with axes swapped', image: '/images/levelmpu6050.png', defineValue: '1', additionalLines: ['#define GYRO_AXIS_SWAP 1'] },
                ]
            },
        },
    ];

    if (stepIndex < 0) {
        return <div />
    }

    let steps = [];

    stepProps.forEach((step, index) => {
        let title = step.title;
        let description;
        if (index < stepIndex) {
            let foundConfig = configuration.find(config => config.variable === stepProps[index].variable);
            if (foundConfig && !Array.isArray(foundConfig.value)) {
                let foundControl = stepProps[index].control.choices.find(choice => foundConfig.value === choice.key);
                description = foundControl.value;
            }
        }

        steps.push(<Step title={title} description={description} />)
    });

    steps.push(<Step title='Completed' />)

    if (showResult) {
        let defines = [];
        configuration.forEach(config => {
            let property = stepProps.find(prop => prop.variable === config.variable);
            let defineLine = null;
            if (property.control.type === 'textinput') {
                if (property.preamble) {
                    defines = [...defines, ...property.preamble];
                }
                property.control.choices.forEach(choice => {
                    let configVal = config.value.find(cfgval => cfgval.key === choice.key);
                    let val = (configVal ? configVal.value : null) || choice.defaultValue || '';
                    defineLine = choice.defineLine.replace('{0}', val);
                    defines = [...defines, defineLine];
                    if (choice.additionalLines){
                        defines = [...defines, ...choice.additionalLines];
                    }
                })
            }
            else {
                let propertyValue = property.control.choices.find(choice => choice.key === config.value);
                if (property.preamble) {
                    defines = [...defines, ...(property.preamble.map((pre) => pre.replace('{v}', propertyValue.value)))];
                }
                defines = [...defines, '#define ' + property.define + ' ' + propertyValue.defineValue];
                if (propertyValue.additionalLines) {
                    defines = [...defines, ...propertyValue.additionalLines];
                }
            }
            defines = [...defines, ''];
        });
        
        return <div className='steps-container'>
            <div className='steps-column'>
                <Steps current={stepIndex} direction='vertical'>
                    {steps}
                </Steps>
            </div>
            <div className='list-container' ref={downloadParentRef}>
                <h2>Local configuration file</h2>
                <p>Copy/paste the following into your Configuration_local.hpp file</p>
                {
                    defines.map(define => <p className='code'>{define}&nbsp;</p>)
                }
                <br />
                <br />
                <div className='back-button' >
                    <Button type='primary' onClick={() => downloadTxtFile(defines)}>Open as Text in new Tab</Button>
                </div>
                

                <div className='back-button' >
                    <Button type='primary' onClick={() => onRestart()}>Restart</Button>
                </div>
            </div>
        </div>

    } else {
        let control = null
        const stepControl = stepProps[stepIndex].control;
        switch (stepControl.type) {
            case 'combo':
                control = <Select onSelect={(e) => onSelect(stepIndex, e)}>
                    {stepControl.choices.map((ch) => <Select.Option value={ch.key}>{ch.value}</Select.Option>)}
                </Select>

                break;

            case 'radio':
                control = <Radio.Group onChange={(e) => onSelect(stepIndex, e.target.value)} buttonStyle='solid'>
                    {stepControl.choices.map((ch) => <Radio.Button value={ch.key}>{ch.value}</Radio.Button>)}
                </Radio.Group>

                break;

            case 'radioimg':
                control = <List
                    bordered
                    itemLayout='horizontal'
                    dataSource={stepControl.choices}
                    renderItem={item =>
                        <List.Item>
                            <Button value={item.value} onClick={(e) => onSelect(stepIndex, item.key)} >{item.value}</Button>
                            <Image className='image-column' src={item.image} />
                        </List.Item>
                    }
                />

                break;

            case 'textinput':
                control = <>
                    { stepControl.choices.map(input =>
                        <div style={{ marginBottom: '10pt' }}>
                            <Input addonBefore={input.label} placeholder={input.label} defaultValue={input.defaultValue} onChange={(e) => onChangedText(stepIndex, input.key, e.target.value)} />
                        </div>
                    )}
                    <div className='back-button' >
                        <Button value='OK' type='primary' onClick={(e) => onChangedText(stepIndex, '$OK')} >Next</Button>
                    </div>
                    <br></br>
                </>

                break;
            default:
                break;
        }

        return <div className='steps-container'>
            <div className='steps-column'>
                <Steps current={stepIndex} direction='vertical'>
                    {steps}
                </Steps>
            </div>
            <div className='list-container'>
                <div className='step-title'>{stepProps[stepIndex].title}</div>
                <div className='step-description'>{stepProps[stepIndex].label}</div>
                <div>
                    {control}
                </div>
                <div className='back-button' >
                    <Button type='primary' onClick={() => setStepIndex(stepIndex - 1)} disabled={stepIndex < 1}>Back</Button>
                </div>
            </div>
        </div>
    }
}

export default WizardStep;
